version = 1

// my name is rahul.

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  type_checker = "mypy"

[[transformers]]
name = "black"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true
