name: CI

on:
  pull_request:
  push:
      branches:
      - master

jobs:
  run-tests:
    runs-on: [ubuntu-latest]

    env:
        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up python3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Run tests
      run: |
        pip install pytest-cov django
        pytest --cov=./ --cov-report=xml
        coverage lcov
        ls -lah

    - name: Wait for 10s (The check should be created at this point)
      uses: juliangruber/sleep-action@v1
      with:
        time: 10s

    - name: Report test coverage to DeepSource
      run: |
        curl https://deepsource.io/cli | sh
        ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml

    - name: Wait for 5s (The check should be created at this point)
      uses: juliangruber/sleep-action@v1
      with:
        time: 5s

    - name: Report test coverage for DeepSource Go
      run: |
        curl https://deepsource.io/cli | sh
        ./bin/deepsource report --analyzer test-coverage --key go --value-file ./coverage.lcov
